### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by neeraj3728** [plivo/plivo-php-examples#1]
I want to use [Sourcegraph](https://sourcegraph.com) for plivo-php-examples code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/plivo/plivo-php-examples. (It should only take 30 seconds.)

Thank you!

**Comment by tsudot** [comment]
Source graph doesn't support PHP
